def print_simulation_output(flight_plan: dict[str, list[str]],
                            map: str) -> None:
    """Prints the step-by-step drone simulation output to the console.

    Outputs each turn of the simulation, listing the drones that
    moved and their
    new destinations (or connections if traversing a waypoint).

    Args:
        flight_plan (dict[str, list[str]]): The flight plan
        generated by TrafficController.
    """
    map_name: str = map.split('/')[-1].split('.')[0]
    if not flight_plan:
        return

    print(f"\n=== {map_name} ===")
    max_turns: int = max(len(plan) for plan in flight_plan.values())

    step: int
    for step in range(1, max_turns):
        line: str = ""
        drone_id: str
        plan: list[str]
        for drone_id, plan in flight_plan.items():
            if step < len(plan):
                if plan[step] != plan[step - 1]:
                    dest: str = plan[step]
                    if dest.startswith("wp_"):
                        dest = dest[3:].replace("_", "-")
                    line += f"{drone_id}-{dest} "
        if line:
            print(line.strip())
    print("======================")
